name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - AssetBundleLoadingTools/**
    - AssetBundleLoadingTools.sln

jobs:
  build:
    name: AssetBundleLoadingTools
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\AssetBundleLoadingTools\manifest.json"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Download dependencies
      uses: nicoco007/download-beatmods-deps@main
      with:
        manifest: ${{ github.workspace }}\AssetBundleLoadingTools\manifest.json
        path: ${{ runner.temp }}\BeatSaberBindings

    - name: Build Debug
      run: dotnet publish ${{ github.workspace }}\AssetBundleLoadingTools\AssetBundleLoadingTools.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: AssetBundleLoadingTools-${{ env.ZIP_VERSION }}-DEBUG
        path: ${{ github.workspace }}\AssetBundleLoadingTools\bin\Debug\Artifact

    - name: Build Release
      run: dotnet publish ${{ github.workspace }}\AssetBundleLoadingTools\AssetBundleLoadingTools.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: AssetBundleLoadingTools-${{ env.ZIP_VERSION }}-RELEASE
        path: ${{ github.workspace }}\AssetBundleLoadingTools\bin\Release\Artifact
